
[TopLeftOverview]
Enabled             = true
reactivity          = 500
sensitivity         = 30


[WindowsButton]
Enabled             = false
reactivity          = 500
sensitivity         = 50


[KeepAwake]
Enabled = true

